DROP DATABASE QRContest;
CREATE DATABASE QRContest;
USE QRContest;

CREATE TABLE QRs(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME TEXT,
    DATA TEXT,
    VALUE INT,
    ACTIVE INT
);

CREATE TABLE Users(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME TEXT,
    PASS TEXT,
    SIGNUPTIME DATETIME,
    LASTONLINE DATETIME,
    SUPERUSER INT
);

CREATE TABLE CollectedQRs(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_USER INT,
    ID_QR INT,
    TIME DATETIME,
    CONSTRAINT FK_USER FOREIGN KEY (ID_USER) REFERENCES Users(ID),
    CONSTRAINT FK_QR FOREIGN KEY (ID_QR) REFERENCES QRs(ID)
);


